wso2/helm-apim

all-in-one/confs/deployment.toml, all-in-one/values.yaml, distributed/control-plane/confs/instance-1/deployment.toml, distributed/control-plane/confs/instance-2/deployment.toml, distributed/control-plane/values.yaml
fixes https://github.com/wso2/api-manager/issues/2714
=> Templating APK related configurations

all-in-one/confs/api-manager.sh, all-in-one/templates/am/wso2am-deployment.yaml, distributed/control-plane/confs/api-manager.sh, distributed/control-plane/templates/control-plane/instance-1/wso2am-cp-deployment.yaml, distributed/control-plane/templates/control-plane/instance-2/wso2am-cp-deployment.yaml
part fix for: https://github.com/wso2/apk/issues/2186
=> Fixing helm template changes

all-in-one/Chart.yaml, distributed/control-plane/Chart.yaml, distributed/gateway/Chart.yaml, distributed/traffic-manager/Chart.yaml
part fix for: https://github.com/wso2/apk/issues/2186
=> Change chart yamls for release

all-in-one/confs/deployment.toml, all-in-one/values.yaml, distributed/control-plane/confs/instance-1/deployment.toml, distributed/control-plane/values.yaml
fixes : https://github.com/wso2/apk/issues/2219
=> Adding missing configuration templates related to APK

all-in-one/confs/deployment.toml, distributed/control-plane/confs/instance-1/deployment.toml
=> Fixing helm template issues

all-in-one/Chart.yaml, distributed/control-plane/Chart.yaml, distributed/gateway/Chart.yaml, distributed/traffic-manager/Chart.yaml
Changing chart version to beta
=> Changing chart version to beta

all-in-one/Chart.yaml, distributed/control-plane/Chart.yaml, distributed/gateway/Chart.yaml, distributed/traffic-manager/Chart.yaml
changing helm chart version to RC
=> changing helm chart version to RC

all-in-one/Chart.yaml, distributed/control-plane/Chart.yaml, distributed/gateway/Chart.yaml, distributed/traffic-manager/Chart.yaml
Changing helm chart version to 1.1.0
=> Changing helm chart version to 1.1.0

all-in-one/Chart.yaml, all-in-one/README.md, all-in-one/confs/deployment.toml, all-in-one/values.yaml, distributed/control-plane/Chart.yaml, distributed/control-plane/README.md, distributed/control-plane/confs/instance-1/deployment.toml, distributed/control-plane/confs/instance-2/deployment.toml, distributed/control-plane/values.yaml, distributed/gateway/Chart.yaml, distributed/gateway/README.md, distributed/gateway/confs/deployment.toml, distributed/gateway/values.yaml, distributed/traffic-manager/Chart.yaml, distributed/traffic-manager/README.md, distributed/traffic-manager/values.yaml
Add AI related configurations to all profiles and parameterized it in values.yaml.
Updated the helm docs to reflect latest changes.
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6292
=> Add AI related configurations and update helm docs

all-in-one/confs/deployment.toml, all-in-one/templates/am/wso2am-conf-script.yaml, all-in-one/templates/am/wso2am-deployment.yaml, all-in-one/values.yaml, distributed/control-plane/confs/instance-1/deployment.toml, distributed/control-plane/confs/instance-2/deployment.toml, distributed/control-plane/templates/control-plane/instance-1/wso2am-cp-deployment.yaml, distributed/control-plane/templates/control-plane/instance-2/wso2am-cp-deployment.yaml, distributed/control-plane/templates/control-plane/wso2am-conf-script.yaml, distributed/control-plane/values.yaml, distributed/gateway/confs/deployment.toml, distributed/gateway/templates/gateway/wso2am-conf-script.yaml, distributed/gateway/templates/gateway/wso2am-gateway-deployment.yaml, distributed/gateway/values.yaml, distributed/traffic-manager/templates/traffic-manager/instance-1/wso2am-tm-deployment.yaml, distributed/traffic-manager/templates/traffic-manager/instance-2/wso2am-tm-deployment.yaml, distributed/traffic-manager/templates/traffic-manager/wso2am-conf-script.yaml, distributed/traffic-manager/values.yaml
$subject
Fixes https://github.com/wso2/helm-apim/issues/32 and https://github.com/wso2/helm-apim/issues/30
=> Add improvements to the helm charts

all-in-one/confs/deployment.toml, all-in-one/values.yaml, distributed/control-plane/confs/instance-1/deployment.toml, distributed/control-plane/confs/instance-2/deployment.toml, distributed/control-plane/values.yaml, distributed/gateway/confs/deployment.toml, distributed/gateway/values.yaml
This PR templating newly added APIM configurations into the All in one and Distributed Helm charts for WSO2 API Manager 4.4.0-Alpha release.
=> [4.4.0] Template Newly Added Configurations for the 4.4.0-Alpha Release Helm Charts

all-in-one/Chart.yaml, all-in-one/README.md, all-in-one/values.yaml, distributed/control-plane/Chart.yaml, distributed/control-plane/README.md, distributed/control-plane/values.yaml, distributed/gateway/Chart.yaml, distributed/gateway/README.md, distributed/gateway/values.yaml, distributed/traffic-manager/Chart.yaml, distributed/traffic-manager/README.md, distributed/traffic-manager/values.yaml
=> Update APIM version

all-in-one/confs/deployment.toml
This PR fixes deployment.toml templating issue.
=> [4.3.x] Fix deployment.toml templating issue

distributed/control-plane/Chart.yaml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update chart yaml for rc

all-in-one/default_values.yaml
=> Add default value set

all-in-one/README.md, all-in-one/default_values.yaml, all-in-one/templates/_helpers.tpl, all-in-one/templates/am/wso2am-deployment.yaml, all-in-one/templates/secrets/wso2am-secret-docker-registry.yaml, all-in-one/values.yaml, distributed/control-plane/README.md, distributed/control-plane/confs/instance-2/deployment.toml, distributed/control-plane/templates/control-plane/instance-1/wso2am-cp-deployment.yaml, distributed/control-plane/templates/control-plane/instance-2/wso2am-cp-deployment.yaml, distributed/control-plane/templates/secrets/_helpers.tpl, distributed/control-plane/templates/secrets/wso2am-secret-docker-registry.yaml, distributed/control-plane/values.yaml, distributed/gateway/README.md, distributed/gateway/templates/gateway/wso2am-gateway-deployment.yaml, distributed/gateway/templates/secrets/_helpers.tpl, distributed/gateway/templates/secrets/wso2am-secret-docker-registry.yaml, distributed/gateway/values.yaml, distributed/key-manager/README.md, distributed/key-manager/templates/key-manager/wso2am-km-deployment.yaml, distributed/key-manager/templates/secrets/_helpers.tpl, distributed/key-manager/templates/secrets/wso2am-secret-docker-registry.yaml, distributed/key-manager/values.yaml, distributed/traffic-manager/README.md, distributed/traffic-manager/templates/secrets/_helpers.tpl, distributed/traffic-manager/templates/secrets/wso2am-secret-docker-registry.yaml, distributed/traffic-manager/templates/traffic-manager/instance-1/wso2am-tm-deployment.yaml, distributed/traffic-manager/templates/traffic-manager/instance-2/wso2am-tm-deployment.yaml, distributed/traffic-manager/values.yaml
This update addresses the need for enhanced deployment flexibility and security in WSO2 API Manager Helm charts. Specifically, it introduces support for private container registries and improves access control configurations. These changes respond to user requirements for secure image pulling in restricted environments and more granular organization-level access management.
The goal of this enhancement is to:
Enable the use of private container registries by allowing users to configure imagePullSecrets.
Improve database configuration defaults for better out-of-the-box reliability.
Introduce optional organization-based access control for fine-grained authorization.
Update documentation to reflect the above capabilities and ensure ease of adoption.
To meet these goals, the following …
=> 4.5.x sync with main

docs/README.md, docs/am-pattern-3-ACP_TM_GW/README.md, docs/am-pattern-4-ACP_TM_GW_KM/README.md, docs/openshift_deployment.md
=> 4.5.x docs - OpenShift

all-in-one/templates/am/wso2am-gateway-ingress.yaml, all-in-one/templates/am/wso2am-ingress.yaml, all-in-one/templates/am/wso2am-websocket-ingress.yaml, all-in-one/templates/am/wso2am-websub-ingress.yaml, all-in-one/values.yaml
=> Fixing TLS secretName Indentation in Ingress Template

all-in-one/Chart.yaml, all-in-one/README.md, distributed/control-plane/Chart.yaml, distributed/control-plane/README.md, distributed/gateway/Chart.yaml, distributed/gateway/README.md, distributed/key-manager/Chart.yaml, distributed/key-manager/README.md, distributed/traffic-manager/Chart.yaml, distributed/traffic-manager/README.md
- Update chart version
- Update helm-docs
=> Update chart version to 4.5.0 3 - 4.5.x

all-in-one/Chart.yaml, all-in-one/README.md, distributed/control-plane/Chart.yaml, distributed/control-plane/README.md, distributed/gateway/Chart.yaml, distributed/gateway/README.md, distributed/key-manager/Chart.yaml, distributed/key-manager/README.md, distributed/traffic-manager/Chart.yaml, distributed/traffic-manager/README.md
=> Update chart version

distributed/gateway/README.md, distributed/gateway/values.yaml, distributed/traffic-manager/README.md, distributed/traffic-manager/values.yaml, docs/am-pattern-2-all-in-one_GW/README.md, docs/am-pattern-2-all-in-one_GW/default_gw_values.yaml, docs/am-pattern-3-ACP_TM_GW/README.md, docs/am-pattern-3-ACP_TM_GW/default_gw_values.yaml, docs/am-pattern-3-ACP_TM_GW/default_tm_values.yaml, docs/am-pattern-4-ACP_TM_GW_KM/README.md, docs/am-pattern-4-ACP_TM_GW_KM/default_gw_values.yaml, docs/am-pattern-4-ACP_TM_GW_KM/default_tm_values.yaml, docs/am-pattern-5-all-in-one_GW_KM/README.md, docs/am-pattern-5-all-in-one_GW_KM/default_gw_values.yaml
- Related to wso2-enterprise/wso2-apim-internal#10176
- Add Km service port. Currently the service port is missing.
- Update docs accordingly.
=> [4.5.x] Add Km service port

all-in-one/Chart.yaml, all-in-one/README.md, all-in-one/default_values.yaml, distributed/control-plane/Chart.yaml, distributed/control-plane/README.md, distributed/gateway/Chart.yaml, distributed/gateway/README.md, distributed/key-manager/Chart.yaml, distributed/key-manager/README.md, distributed/traffic-manager/Chart.yaml, distributed/traffic-manager/README.md
=> Update helm resources for 4.6.0 Alpha3 release
